### ISSUE TITLE
Can I use more than 8 colors?

### ISSUE THREAD

**Issue by KillaPL** [ruby/curses#17]
Hi

I can use 8 colors provided, but I would very much like to use more than that. Is there any nice way for me to define my own colors? I can't find any reasonable resources on this idea.
This might be helpful: `can_change_colors?`, returns false for me, but I have no idea why. 

```
puts "\e[1;90mt\e[0m"
```

will render me a nice, grey "t"

**Comment by drbrain** [comment]
This depends upon your curses version, it seems. [ncurses 6.0](http://invisible-island.net/ncurses/announce-6.0.html) seems to support more than 16 colors:

> Extend the cchar_t structure to allow more than 16 colors to be encoded.

**Comment by KillaPL** [comment]
It would seem that I have ncurses 5 installed (I'm using ubuntu 14.04). Does that mean no colors for me, if I'm not willing to install ncurses 6?

**Comment by drbrain** [comment]
You will need to upgrade to ncurses 6 to get more than 8 colors (I'm guessing it ncurses 5 supports 8 foreground and 8 background).

The curses gem may need an update to support more colors too, so I am leaving this open.

**Comment by KillaPL** [comment]
Understood, thank you for your answers.

**Comment by shugo** [comment]
It seems that the problem has been solved, so I close this issue.
