### ISSUE TITLE
no `A_UNDERLINE` effect in tmux

### ISSUE THREAD

**Issue by ta1kt0me** [ruby/curses#22]
There is no `A_UNDERLINE` effect in tmux on Mac. This problem reproduces below.
https://gist.github.com/ta1kt0me/d890ef0b25513be40e2e1e3b60d0d51a

- OS: Mac OS Sierra
- Ruby: 2.4.0p0
- tmux: 2.3
- curses: 1.2.0

## note

If don't use tmux, enable `A_UNDERLINE` effect.

- not use tmux

<img width="307" alt="2017-02-21 1 29 18" src="https://cloud.githubusercontent.com/assets/1412864/23133749/8ed21d08-f7d5-11e6-9132-5f2a21be6b41.png">

- use tmux

<img width="339" alt="2017-02-21 1 29 00" src="https://cloud.githubusercontent.com/assets/1412864/23133763/9bd76e90-f7d5-11e6-8f4e-4bbec5d02d84.png">

**Comment by drbrain** [comment]
This seems to be a termcap issue, does [this article's command](http://hoppsjots.org/?p=177) fix it:

```
$({ infocmp -x screen-256color;
    printf '\t%s\n' 'ncv@,'; } > /tmp/t && tic -x /tmp/t)
```

**Comment by ta1kt0me** [comment]
thanks!
