### ISSUE TITLE
Window#getch called twice for unicode characters.

### ISSUE THREAD

**Issue by botanicus** [ruby/curses#35]
This is basically what's been reported here https://bugs.ruby-lang.org/issues/9094

In my case I'm getting `195` and `169` for `é`, but really it's exactly the same issue like Johan described in the link above.

Cheers,

J

**Comment by botanicus** [comment]
In the meantime, any idea of how to get `é` out of `195` and `169` would be very appreciated.

**Comment by thatdutchguy** [comment]
@botanicus as a work-around, you could use something like:

    [195, 169].pack('C*').force_encoding(Encoding::UTF_8)
    => "é"

Or for longer sequences of characters, something along the lines of:

    raw = "".encode(Encoding::UTF_8)
    StringIO.open(raw) do |io|
      io.write [72, 195, 169, 108, 108, 111].pack('C*')
    end
    raw
    => "Héllo"

**Comment by shugo** [comment]
@botanicus 
Window#getch doesn't support multibyte characters.
Could you try Window#get_char instead?

You may have to set Curses.keyboard_encoding if it's not appropriate.
