### ISSUE TITLE
Using / downloading Curses on ruby 2.3.0

### ISSUE THREAD

**Issue by OmG3r** [ruby/curses#36]
I downloaded curses using "gem install curses", while using ruby 2.3.0 whenever i attempt to start a script in which i used curses i get " 

C:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:5
5:in `require': cannot load such file -- curses.so (LoadError)
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel
_require.rb:55:in `require'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/curses-1.2.3-x
86-mingw32/lib/curses.rb:17:in `rescue in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/curses-1.2.3-x
86-mingw32/lib/curses.rb:13:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel
_require.rb:127:in `require'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel
_require.rb:127:in `rescue in require'
        from C:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel
_require.rb:40:in `require'
        from test.rb:1:in `<main>'
tried in 3 different computers, all 2.3.0 ruby version

**Comment by OmG3r** [comment]
After checking other versions, i was able to use the gem on ruby 2.2.6, and unable to use it on ruby 2.4.1

**Comment by shugo** [comment]
@OmG3r 
I've released 1.2.4 to fix this problem.
Could you try it?

**Comment by OmG3r** [comment]
Works on ruby 2.3.3, however it does not work on ruby 2.4.1

**Comment by plonk** [comment]
I'm having the same issue with ruby 2.4.2. It says on [the RubyInstaller page](https://rubyinstaller.org/downloads/) that they have switched to the MSYS2 toolkit. Could that somehow be related?

![image](https://user-images.githubusercontent.com/1680210/31104195-85b2f0f2-a816-11e7-9e78-1f6c6b1a70ce.png)

**Comment by littlepinkbeast** [comment]
This is exactly what I was running into: works fine on 2.3, but not on 2.4 yet.

**Comment by soanvig** [comment]
This problem only touches Windows users.

**Comment by shugo** [comment]
This problem has been fixed in 1.2.7 by linking PDCurses statically.
