### ISSUE TITLE
.box() doesn't work with UTF-8

### ISSUE THREAD

**Issue by soanvig** [ruby/curses#38]
Hi.

The `.box()` method does not work with UTF-8 characters.

`window.box('│', '─')` leads to displaying `â` character (it is grey rectangle in my terminal).

Where these dashes are [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) copied directly into the code (with unicode transcription it doesn't work either).

What works however is UTF-8, but with `.addstr()` method.

Curses 1.2.4
Ruby 2.4
Fedora 25

**Comment by shugo** [comment]
The following C program also doesn't work with ncurses.

```
#include <ncurses.h>

int main()
{
    initscr();

    WINDOW *win = newwin(9, 40, 5, 20);
    mvwaddstr(win, 4, 15, "Hit ay key");
    box(win, 0x2502, 0x2500);
    touchwin(win);
    wrefresh(win);

    getchar();

    endwin();
    return 0;
}
```

Do you have any version of curses whose box() supports Unicode?

**Comment by sh7d** [comment]
This is not problem of ruby curses bindings, using chars like that is more complicated in ncurses in general
Try something like that:
```ruby
win.attron(Curses::A_ALTCHARSET)
win.box(120, 113)
win.attroff(Curses::A_ALTCHARSET)
win.refresh
```
Keyword: Ncurses extended character :)
There should be constants from original ncurses library embedded into ruby curses bindings, but currently there arent any :(

**Comment by shugo** [comment]
@sh7d Thanks for your comment.

I close this issue because it's not an issue of Ruby bindings.
