### ISSUE TITLE
Understanding how to redefine colors and pairs

### ISSUE THREAD

**Issue by kaspergrubbe** [ruby/curses#42]
Hi, 

This has been bugging me for a while, and I do not know if I am doing something wrong, or if it is a bug in either `curses`, `ncurses` or in my terminal.

I have created a fairly elaborate script that first loads in a colorscheme, I have stolen the material colors scheme from Android to work with (please see the `material-colors.json` file here: https://gist.github.com/kaspergrubbe/f6e64178e3962a3609e93569dc7722ce). It then reads all the hex values, and converts it to ncurses (between 0 and 1000) like this:

```ruby
@red = 'ff'
@green = 'ff'
@blue = 'ff'
[@red, @green, @blue].map{|h| h.hex / 0.255}.map(&:to_i)
#=> [1000, 1000, 1000]
```

I then read the `materials-colors.json` file, it is grouped by colorname and a weight like so:

```json
{
  "red": {
    "50": "#ffebee",
    "100": "#ffcdd2",
    "300": "#e57373",
    "500": "#f44336",
    "700": "#d32f2f",
    "800": "#c62828",
    "900": "#b71c1c"
  },
  "pink": {
    "50": "#fce4ec",
    "100": "#f8bbd0",
    "300": "#f06292",
    "500": "#e91e63",
snipped
```

I then load in all the individual colours, calculate all possible combination of colour pairs where each color can be both front and back, and then I initialise `curses` and get it to setup the colours.

I then print `lol` 5 times:

```ruby
  fg = @colour_map['grey']['50']
  bg = @colour_map['lightblue']['900']
  pair = @colour_map.pair(fg, bg)

  paint_effect(win, Curses.color_pair(pair.number) | Curses::A_UNDERLINE) do
    win.setpos(1,1)
    win.addstr('lol')
  end

  paint_effect(win, Curses.color_pair(1337) | Curses::A_UNDERLINE) do
    win.setpos(2,2)
    win.addstr('lol')
  end

  paint_effect(win, Curses.color_pair(10337) | Curses::A_UNDERLINE) do
    win.setpos(3,3)
    win.addstr('lol')
  end

  paint_effect(win, Curses.color_pair(0)) do
    win.setpos(4,4)
    win.addstr('lol')
  end

  paint_effect(win, Curses.color_pair(@colour_map.pair(@colour_map['grey']['50'], @colour_map['blue']['900']).number)) do
    win.setpos(5,5)
    win.addstr('lol')
  end
```

But the results are very strange. This is how iTerm renders it:

<img width="411" alt="screenie_1540816453_064939" src="https://user-images.githubusercontent.com/334273/47650083-0bc74500-db77-11e8-8bae-b94f514c7903.png">

If you hover over it, you can see that it writes some text:

<img width="195" alt="screenie_1540816517_8422852" src="https://user-images.githubusercontent.com/334273/47650104-1d105180-db77-11e8-9a8e-d1d1b545e3fa.png">

And the OSX Terminal.app renders it very differently:

![ncurses_terminal_render](https://user-images.githubusercontent.com/334273/47650241-8d1ed780-db77-11e8-97c8-49bf5dd4ffe9.gif)

However, while Terminal.app manages to reset the colors after the program exits, the same cannot be said about iTerm:

Before:
<img width="588" alt="screenie_1540816908_153203" src="https://user-images.githubusercontent.com/334273/47650395-06b6c580-db78-11e8-9338-15f34bcbb3dd.png">

After:
<img width="557" alt="screenie_1540816926_967733" src="https://user-images.githubusercontent.com/334273/47650405-11715a80-db78-11e8-9f70-723c4e768bb0.png">

I have made a whole repo here: https://github.com/kaspergrubbe/curses_colortest the only thing to test is just cloning the repo and running `ruby colortest.rb`.

Can you see something I can't?

**Comment by kaspergrubbe** [comment]
I would like to add a $50 bug bounty that fixes this issue, or help me get https://github.com/kaspergrubbe/curses_colortest to render properly. 

@shugo or @hsbt if you know anyone I could reach out to that might be interested in looking into this issue please point them in this direction, please.

**Comment by kaspergrubbe** [comment]
It seems to mess up the characters when I use a `color_pair` higher than `16383`:

<img width="123" alt="screenie_1541552199_000484" src="https://user-images.githubusercontent.com/334273/48103678-1a24f900-e228-11e8-9d1b-612e2d6446ca.png">

But under works fine:

<img width="133" alt="screenie_1541552257_2636921" src="https://user-images.githubusercontent.com/334273/48103690-23ae6100-e228-11e8-84a9-1be0c72ad7f7.png">

**Comment by kaspergrubbe** [comment]
Everything is working when using ncurses 6.1 by compiling curses with ncurses from Homebrew:

```
bundle config build.curses --with-cflags="-I$(brew --prefix)/opt/ncurses/include" --with-ldflags="-L$(brew --prefix)/opt/ncurses/lib"
```

**Comment by rubyFeedback** [comment]
Can you also add the code for the .rb file? I'd love to reproduce this.

**Comment by kaspergrubbe** [comment]
@rubyFeedback Hi, first: Thanks for your interest in curses in Ruby, it's something I haven't played with for a while, but it's a fascinating world creating TUIs, it's a dark art, and things are a bit low-level and sometimes a little wonky :)

I think all the code is available here: https://github.com/kaspergrubbe/curses_colortest is there anything else you're missing? :)
