### ISSUE TITLE
Curses 1.3.1 not installing with Ruby <=2.4.4 on Ubuntu 19.04

### ISSUE THREAD

**Issue by paulgoetze** [ruby/curses#51]
When running `gem install curses` on Ubuntu 19.04 building the native extension for curses v1.3.1 fails for Ruby versions <=2.4.4. libncursesw5-dev and libncurses5-dev are installed. I tried with C-Ruby versions installed via RVM.

Because the failure logs are about 4900 lines long, I’ll attach them as a file:
[curses-1.3.1.zip](https://github.com/ruby/curses/files/3775606/curses-1.3.1.zip)

Installing the gem works for me for Ruby >=2.4.5.

**Comment by shugo** [comment]
The same errors are reported at <https://gitlab.com/gitlab-org/prometheus-client-mmap/issues/26>.

It seems that Ruby 2.4.4 has problems with new versions of gcc.
Please use Ruby 2.4.5 or later.
