### ISSUE TITLE
Misleading installation instructions for Windows in readme.md

### ISSUE THREAD

**Issue by jjgh** [ruby/curses#53]
I noticed that on Windows the curses gem can be currently installed with just `gem install curses`.
Why is this not clearly written in the readme?

I was under the impression that a binary was not available for windows so I lost a lot of time looking for other ways to install it!

It should be more clear that on Windows all you have to do is "gem install curses".

**Comment by shugo** [comment]
I've added a note for installation on mingw in da3a3c76.
