### ISSUE TITLE
uninitialized constant BUTTON1_CLICKED (NameError)

### ISSUE THREAD

**Issue by jjgh** [ruby/curses#54]
I'm trying to run the example at https://github.com/ruby/curses/blob/master/sample/mouse.rb and I'm getting this error:

`test-curses.rb:29:in <main>: uninitialized constant BUTTON1_CLICKED (NameError)`

I'm on Ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32] running on Windows 10.

**Comment by shugo** [comment]
Unfortunately, It seems that the feature is not supported on mingw32(PDCurses).

**Comment by illtellyoulater** [comment]
@shugo I see, but I think it should be supported with ncurses, right? Maybe I will try with `gem install curses -- --use-system-libraries` and see what happens. Thank you!
