### ISSUE TITLE
Not Displaying Wide Characters

### ISSUE THREAD

**Issue by ninp0** [ruby/curses#61]
Despite:

```
$ sudo apt install libncursesw5 libncursesw5-dev
```

window.box(' ', "\u2500")

outputs a horizontal block of gray text instead of a nice horizontal box line.

What steps are needed to display wide unicode characters using the curses gem?

I can confirm the version of ruby does properly output the unicode I expect:

```
 puts "\u2500"*9
─────────
```

**Comment by shugo** [comment]
box doesn't support multibyte characters.
Try the following code to check multibyte support:

```
Curses.init_screen
Curses.addstr("\u2500" * 9 + "\nEnter: ")
Curses.getch
Curses.close_screen
```

**Comment by ninp0** [comment]
That worked for my needs - thanks!
