### ISSUE TITLE
Are some files missing on the .gem release?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/curses#64]
So I just installed the curses-1.4.1 gem.

However had, in the sample/ directory I see the following 7 .rb files:

    form.rb
    hello.rb
    menu.rb
    mouse.rb
    rain.rb
    view2.rb
    view.rb

On github, though, if you go here:

https://github.com/ruby/curses/tree/master/sample

You can see 11 files:

    addch.rb
    attr_demo.rb
    colors.rb
    form.rb
    hello.rb
    menu.rb
    mouse.rb
    mouse_move.rb
    rain.rb
    view.rb
    view2.rb 

I am quite confused. Is the gem built from some other source target that explains why 4 files seem to be missing? Or is this some user error?

I am relearning curses (have had old code with Ncurses as toplevel module name) so I randomly looked at attr_demo.rb
first via the browser. Then I wanted a local copy to experiment, and just downloaded the gem, then noticed that some files are missing. Very strange..

**Comment by kaspergrubbe** [comment]
The 1.4.1 branch only have 7 sample files: https://github.com/ruby/curses/tree/v1.4.1/sample

The 4 missing files you're looking for seems to have been added quite recently, so there isn't a release that includes them yet.

**Comment by shugo** [comment]
@kaspergrubbe Thanks for your follow-up.
@rubyFeedback I've just released curses-1.4.2 which includes new sample files.
