### ISSUE TITLE
Curses.get_char fails on multibyte characters

### ISSUE THREAD

**Issue by tjortho** [ruby/curses#67]
I can't capture any of  the multibyte characters (ie. function keys, arrow keys, and ESC) because they are all evaluating to the same thing: "\e".

Description of Curses.get_char:  "Read and returns a character or ***function key*** from the window."  (emphasis mine)

Single byte characters work fine, and escape code characters (\t for tab) work.

Using  version 1.4.3
(I'd like to navigate through text buffers with directional keys)

Thank you for any insight or feedback in advance.

**Comment by tjortho** [comment]
Nevermind. I found the "keypad" method in the Window class.

**Comment by shugo** [comment]
Thank you.
