### ISSUE TITLE
gem installation warning: "Couldn't find file to include xyz"

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/curses#77]
I just installed the gem.

Response was:

    Fetching curses-1.4.4.gem
    Building native extensions. This could take a while...
    Successfully installed curses-1.4.4
    Parsing documentation for curses-1.4.4
    Couldn't find file to include 'sample/hello.rb' from ext/curses/curses.c
    Couldn't find file to include 'sample/rain.rb' from ext/curses/curses.c
    Couldn't find file to include 'sample/mouse.rb' from ext/curses/curses.c
    Installing ri documentation for curses-1.4.4
    Done installing documentation for curses after 0 seconds
    1 gem installed

The three warnings relate to some .rb file in sample - see lines starting
from 5-7.

Could these three .rb files be included? hello.rb rain.rb and mouse.rb. Not
sure why they could not be found.

**Comment by shugo** [comment]
Thank you.  I've fixed it in 7113981.
