### ISSUE TITLE
NCURSES_EXT_COLORS - see python

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/curses#80]
https://bugs.python.org/issue36982

"A new function called curses.has_extended_color_support() will indicate whether the linked ncurses library provides extended color support. It returns true if curses.h defines NCURSES_EXT_COLORS and NCURSES_EXT_FUNCS, indicating that the extended color functions are available. This seems more useful to developers than using an indirect method like trying to set a color-pair greater than 0x7fff and checking for an exception to indicate lack of support."

Would this make sense to add for ruby too? E. g. a method such as:

    Curses.has_extended_color_support?

I'd love to be able to use more than 8 colours via ncurses. In particular the html-colours:

https://htmlcolorcodes.com/colors/

I could then add this to my gem e. g.

    CursesParadise.steelblue("Hello world!\n")

As easier alternative.

**Comment by shugo** [comment]
@rubyFeedback Thanks for your proposal.  How about #81?
